apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: myk8sapp-rules
  labels:
    release: prometheus
spec:
  groups:
  - name: myk8sapp.rules
    rules:
    - alert: HighCpuUsage
      expr: sum(rate(container_cpu_usage_seconds_total{pod=~"myk8sapp-.*"}[2m])) by (pod) > 0.5
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage on {{ $labels.pod }}"
        description: "Pod {{ $labels.pod }} CPU usage is > 0.5 cores for 2 minutes."
    - alert: PodRestartSpike
      expr: increase(kube_pod_container_status_restarts_total{pod=~"myk8sapp-.*"}[5m]) > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod restart detected on {{ $labels.pod }}"
