apiVersion: v1
kind: Service
metadata:
  name: myk8sapp-svc
  labels:
    app: myk8sapp
spec:
  selector:
    app: myk8sapp
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
